2024-01-17 12:08:11,855 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:08:51,022 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:266 - C:\Users\Arian\Desktop\Django-JWT\jwt\authorizationApp\urls.py changed, reloading.
2024-01-17 12:08:51,327 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:08:53,524 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:266 - C:\Users\Arian\Desktop\Django-JWT\jwt\authorizationApp\urls.py changed, reloading.
2024-01-17 12:08:53,837 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:09:00,223 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:266 - C:\Users\Arian\Desktop\Django-JWT\jwt\authorizationApp\urls.py changed, reloading.
2024-01-17 12:09:00,541 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:09:15,819 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:11:36,901 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:266 - C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\settings.py changed, reloading.
2024-01-17 12:11:37,228 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:12:01,772 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:266 - C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\settings.py changed, reloading.
2024-01-17 12:12:02,102 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:12:55,082 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:13:44,589 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:14:25,018 WARNING C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\log.py:241 - Unauthorized: /jwt/login/
2024-01-17 12:14:46,684 ERROR C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\log.py:241 - Internal Server Error: /jwt/login/
Traceback (most recent call last):
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\views.py", line 44, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\serializers.py", line 77, in validate
    data["refresh"] = str(refresh)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 95, in __str__
    return self.get_token_backend().encode(self.payload)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 229, in get_token_backend
    return self.token_backend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 222, in token_backend
    self._token_backend = import_string(
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\state.py", line 1, in <module>
    from .backends import TokenBackend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\backends.py", line 8, in <module>
    from jwt import InvalidAlgorithmError, InvalidTokenError, algorithms
ImportError: cannot import name 'InvalidAlgorithmError' from 'jwt' (C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\__init__.py)
2024-01-17 12:17:36,718 INFO C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\autoreload.py:668 - Watching for file changes with StatReloader
2024-01-17 12:17:40,622 ERROR C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\log.py:241 - Internal Server Error: /jwt/login/
Traceback (most recent call last):
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\serializers.py", line 72, in validate
    data["refresh"] = str(refresh)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 81, in __str__
    return self.get_token_backend().encode(self.payload)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 204, in get_token_backend
    return self.token_backend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 197, in token_backend
    self._token_backend = import_string(
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\state.py", line 1, in <module>
    from .backends import TokenBackend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\backends.py", line 7, in <module>
    from jwt import InvalidAlgorithmError, InvalidTokenError, algorithms
ImportError: cannot import name 'InvalidAlgorithmError' from 'jwt' (C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\__init__.py)
2024-01-17 12:17:42,784 ERROR C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\log.py:241 - Internal Server Error: /jwt/login/
Traceback (most recent call last):
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\decorators\csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\serializers.py", line 72, in validate
    data["refresh"] = str(refresh)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 81, in __str__
    return self.get_token_backend().encode(self.payload)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 204, in get_token_backend
    return self.token_backend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\tokens.py", line 197, in token_backend
    self._token_backend = import_string(
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\state.py", line 1, in <module>
    from .backends import TokenBackend
  File "C:\Users\Arian\Desktop\testenv\lib\site-packages\rest_framework_simplejwt\backends.py", line 7, in <module>
    from jwt import InvalidAlgorithmError, InvalidTokenError, algorithms
ImportError: cannot import name 'InvalidAlgorithmError' from 'jwt' (C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\__init__.py)
2024-01-17 12:21:43,215 INFO C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\autoreload.py:636 - Watching for file changes with StatReloader
2024-01-17 12:21:47,052 ERROR C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\log.py:224 - Internal Server Error: /jwt/login/
Traceback (most recent call last):
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\serializers.py", line 72, in validate
    data["refresh"] = str(refresh)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 81, in __str__
    return self.get_token_backend().encode(self.payload)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 204, in get_token_backend
    return self.token_backend
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 197, in token_backend
    self._token_backend = import_string(
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\state.py", line 1, in <module>
    from .backends import TokenBackend
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\backends.py", line 7, in <module>
    from jwt import InvalidAlgorithmError, InvalidTokenError, algorithms
ImportError: cannot import name 'InvalidAlgorithmError' from 'jwt' (C:\Users\Arian\Desktop\Django-JWT\jwt\jwt\__init__.py)
2024-01-17 12:23:05,338 DEBUG C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:630 - Using proactor: IocpProactor
2024-01-17 12:23:05,432 DEBUG C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:630 - Using proactor: IocpProactor
2024-01-17 12:24:13,428 INFO C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\autoreload.py:636 - Watching for file changes with StatReloader
2024-01-17 12:24:16,853 ERROR C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\log.py:224 - Internal Server Error: /jwt/login/
Traceback (most recent call last):
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\views.py", line 43, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\serializers.py", line 227, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework\serializers.py", line 429, in run_validation
    value = self.validate(value)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\serializers.py", line 72, in validate
    data["refresh"] = str(refresh)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 81, in __str__
    return self.get_token_backend().encode(self.payload)
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 204, in get_token_backend
    return self.token_backend
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\tokens.py", line 197, in token_backend
    self._token_backend = import_string(
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\django\utils\module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\state.py", line 1, in <module>
    from .backends import TokenBackend
  File "C:\Users\Arian\Desktop\testenv2\lib\site-packages\rest_framework_simplejwt\backends.py", line 7, in <module>
    from jwt import InvalidAlgorithmError, InvalidTokenError, algorithms
ImportError: cannot import name 'InvalidAlgorithmError' from 'jwt' (C:\Users\Arian\Desktop\Django-JWT\jwt-project\jwt\__init__.py)
2024-01-17 12:24:29,304 DEBUG C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:630 - Using proactor: IocpProactor
2024-01-17 12:24:29,389 DEBUG C:\Users\Arian\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py:630 - Using proactor: IocpProactor
